# Generated by Django 3.2 on 2023-05-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='change',
            field=models.IntegerField(default=1),
        ),
    ]
